# This is a basic workflow to help you get started with Actions

name: Build Docker image sofabuilder_ubuntu

# Controls when the action will run. 
on: [push, workflow_dispatch]

env:
    DOCKERFILE_PATH: docker/sofabuilder_ubuntu

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - 
            name: Checkout source code
            uses: actions/checkout@v2
              
            - 
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
              
            - 
            name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
              
            - 
            name: Build and push
            uses: docker/build-push-action@v2
            with:
                context: ${{ env.DOCKERFILE_PATH }}
                push: true
                tags: sofabuilder_ubuntu:$(date +%Y%m%d_%H%M%S)
            
            #-
            #name: Build Docker image
            #run: |
            #    pwd
            #    ls -la
            #    cd docker/sofabuilder_ubuntu
            #    docker build . --tag sofabuilder_ubuntu:$(date +%Y%m%d_%H%M%S)
            #    echo "----------- BUILD DONE -----------"
            #docker images
